### ISSUE TITLE
Can I set a maximum height?

### ISSUE THREAD

**Issue by AndreRX** [TechFortress/GriefPrevention#1104] opened 2020-11-19 16:17 UTC
when a player claim a land, the height is unlimited, i want a maximum of 30 block.

How can i do that?

**Comment by bigpresh** [comment] 2020-11-19 16:23
GP claims have no max height.

It may be possible for an addon to change that, but I'm not sure, would have to look at the code closely.

I don't imagine that such an option would be likely in GP core, though - it'd add confusion and not be of use to many people.

**Comment by Jikoo** [comment] 2020-12-06 09:56
Duplicate of #269

**Closed by Jikoo** 2020-12-06 09:56 UTC
Labels: Question

**Comment by Jikoo** [comment] 2020-12-06 09:57
I know this specifically requests main claim and not subclaims, but GP treats them roughly the same way, so the same large changes to move from 2D to 3D space would be required.
