### ISSUE TITLE
PlaceholderAPI

### ISSUE THREAD

**Issue by blueawp** [TechFortress/GriefPrevention#926] opened 2020-08-01 23:44 UTC
when i updated to the latest placeholderAPI  "2.10.8* the placeholder {placeholderapi_griefprevention_currentclaim_ownername_color}
stop working

**Comment by Jikoo** [comment] 2020-08-01 23:51
Duplicate of #923

**Comment by Jikoo** [comment] 2020-08-01 23:51
> GP does not provide a PAPI hook, PAPI offers a GP hook. Try re-downloading the hook via their system, and if you still encounter the issue contact PAPI.

**Closed by Jikoo** 2020-08-01 23:51 UTC
Labels: Question
