### ISSUE TITLE
Summarize your question into a single sentence here

### ISSUE THREAD

**Issue by lostINParadies** [TechFortress/GriefPrevention#767] opened 2020-04-03 12:20 UTC
Hey,
Can there be a option to set the minimum distance between claims from different players?
so that if I have a claim, that the other player can only claim 100 block away from my claim. 

Thanks

**Comment by Jikoo** [comment] 2020-04-03 13:07
Duplicate of #768

**Closed by Jikoo** 2020-04-03 13:07 UTC
Labels: Question
